modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/tangsoon/tangsoon.github.io/issues" #optional
[[mods]] #mandatory
modId="hmxy" #mandatory
version="0.0.0.3" #mandatory ${version} 
displayName="鸿蒙仙缘" #mandatory
updateJSONURL="https://tangsoon.github.io/updates.json" #optional
displayURL="https://tangsoon.github.io/" #optional
logoFile="pack.png" #optional
credits="by 指间青春(tangsoon)"
authors="指间青春(tangsoon)" #optional
description="\n道友，修个仙吗？\n"

[[dependencies.hmxy]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.hmxy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.18.2]"
    ordering="NONE"
    side="BOTH"
[modproperties.hmxy]
    catalogueImageIcon="catalogue.png"
    configuredBackground="minecraft:textures/block/stone.png"