modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="hmxy" #mandatory
version="0.0.0.2" #mandatory ${version} 
displayName="鸿蒙仙缘" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="pack.png" #optional
credits="by 指间青春(tangsoon)"
authors="指间青春(tangsoon)" #optional
description="\n道友，修个仙吗？。\n"

[[dependencies.hmxy]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.hmxy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.18.2]"
    ordering="NONE"
    side="BOTH"
[modproperties.hmxy]
    catalogueImageIcon="catalogue.png"
    configuredBackground="minecraft:textures/block/stone.png"