modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="hmxy" #mandatory
version="0.0.0.1" #mandatory
displayName="鸿蒙仙缘" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="logo.png" #optional
credits='''感谢以下作者的奉献：
*手书体和智勇手书英文体来自(知乎用户：Joker9)https://www.zhihu.com/question/19889152/answer/767066635 ;
'''
authors="指间青春" #optional
description='''
道友，修个仙吗？。
'''
[[dependencies.hmxy]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.hmxy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
